apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-provisioner-prow-rc
imageTag:
  name: k8s.gcr.io/sig-storage/csi-provisioner
  newTag: "v1.6.1"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-resize-prow-rc
imageTag:
  name: k8s.gcr.io/sig-storage/csi-resizer
  newTag: "v1.1.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-node-registrar-prow-rc
imageTag:
  name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  newTag: "v1.3.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-gce-fs-driver-rc
imageTag:
  name: k8s.gcr.io/cloud-provider-gcp/gcp-filestore-csi-driver
  newTag: "v0.4.0"
---
