apiVersion: v1
kind: Namespace
metadata:
  name: gke-managed-filestorecsi

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filestorecsi-node-driver-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "delete", "update", "create"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filestorecsi-node-driver-role
  namespace: gke-managed-filestorecsi
subjects:
  - kind: ServiceAccount
    name: gcp-filestore-csi-node-sa
    namespace: gcp-filestore-csi-driver
roleRef:
  kind: ClusterRole
  name: filestorecsi-node-driver-role
  apiGroup: rbac.authorization.k8s.io
