apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../stable-master
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: gcp-filestore-csi-controller
  path: snapshotter_http_endpoint.yaml
transformers:
- ../../images/prow-gke-release-staging-rc-master
