apiVersion: v1
kind: Pod
metadata:
  name: web-server-1
spec:
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - mountPath: /usr/share/nginx/html
         name: mypvc
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: preprov-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: preprov-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-filestore
  resources:
    requests:
      storage: 1Ti