apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:
  gcp-filestore-csi-driver
resources:
- ../../base/controller
- ../../base/node_linux
transformers:
- ../../images/stable-1-17
