apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-delayed-binding-allowedtopo
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: test-pvc-fs-delayed-binding-allowedtopo
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-fs-delayed-binding-allowedtopo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-filestore-delayed-binding-allowedtopo
  resources:
    requests:
      storage: 1Ti
