apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-filestore-delayed-binding-allowedtopo
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: topology.gke.io/zone
    # Replace the values with a subset of zones of the regional cluster
    values:
    - us-central1-a
    - us-central1-b
