apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: gcp-filestore-csi-controller-psp
spec:
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - "emptyDir"
    - "secret"
  hostNetwork: true
