apiVersion: v1
kind: Pod
metadata:
  name: restored-pod
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "3600"
    volumeMounts:
    - name: source-data
      mountPath: /demo/data
  volumes:
  - name: source-data
    persistentVolumeClaim:
      claimName: restored-pvc
      readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: restored-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-filestore
  resources:
    requests:
      storage: 1Ti
  dataSource:
    kind: VolumeSnapshot
    name: backup-source-pvc
    apiGroup: snapshot.storage.k8s.io
