apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:
  gcp-filestore-csi-driver
resources:
- ../../base/controller
- ../../base/node_linux
patchesStrategicMerge:
- fsgrouppolicy.yaml
transformers:
- ../../images/stable-master
