apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: test-pvc-fs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-fs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-filestore
  resources:
    requests:
      storage: 1Ti
